"""empty message

Revision ID: 6c5f34ab290c
Revises: 
Create Date: 2018-08-20 17:25:00.387108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c5f34ab290c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_information', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_information', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
